export default {
    input: {
        search: 'mdi-magnify',
        task: '',
        my_application: 'mdi mdi-format-list-checkbox',
        workflow_definition: "mdi-lan",
        document_definition: "mdi-file-document-edit-outline",
        document: "mdi mdi-import",
        document_instance: 'mdi mdi-file-document-outline',
        BI: "mdi-view-dashboard-outline",
        orgchart: "mdi-office-building-outline",
        lisTaskToDo: "mdi-sticker-check-outline",
        timeTable: "mdi-calendar-month-outline",
        knowledge: 'mdi-file-certificate-outline',
        file: 'mdi-upload-outline',
        userManager: "mdi-account-cog-outline",
        user: "mdi-account-cog-outline",
        accessManager: "mdi-shield-key-outline",
        application_definition: "mdi mdi-widgets-outline",
        account: 'mdi-account-multiple-outline',
        process_definition: "mdi mdi-sitemap",
        application_definition: "mdi mdi-apps",
        syql: "mdi mdi-alpha-f",
        dataflow: "mdi mdi-arrange-send-to-back",
        comment: "mdi-comment-outline",
        file: "mdi mdi-file-upload-outline",
        dashboard: "mdi mdi-view-dashboard",
        action_pack: " mdi mdi-package-variant-closed",
        import: "mdi mdi-import",
        taskBPM: "mdi-lan",
        task: "mdi-hand-left",
        role: "mdi mdi-account-circle-outline",
        time_sheet: "mdi mdi-calendar-month-outline"
    }
}